apiVersion: v2
name: openeo-studio
description: Interactive code editor for openEO satellite imagery processing
type: application
version: 0.1.0
appVersion: "0.1.1"
home: https://github.com/developmentseed/openeo-studio
sources:
  - https://github.com/developmentseed/openeo-studio
maintainers:
  - name: Development Seed
    url: https://developmentseed.org
