name: Deploy Github Pages

on:
  push:
    branches:
    - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: '.nvmrc'

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        name: Install pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Cache dist
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        id: cache-dist
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Build
        env:
          VITE_BASE_URL: ${{ vars.VITE_BASE_URL }}
          VITE_APP_TITLE: ${{ vars.VITE_APP_TITLE }}
          VITE_APP_DESCRIPTION: ${{ vars.VITE_APP_DESCRIPTION }}
          VITE_MAPTILER_KEY: ${{ vars.VITE_MAPTILER_KEY }}
          VITE_AUTH_AUTHORITY: ${{ vars.VITE_AUTH_AUTHORITY }}
          VITE_AUTH_CLIENT_ID: ${{ vars.VITE_AUTH_CLIENT_ID }}
          VITE_AUTH_REDIRECT_URI: ${{ vars.VITE_AUTH_REDIRECT_URI }}
          VITE_ENABLE_NARRATIVE_EXPORT: ${{ vars.VITE_ENABLE_NARRATIVE_EXPORT }}
        run: pnpm build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Restore dist cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        id: cache-dist
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
        with:
          branch: gh-pages
          clean: true
          single-commit: true
          folder: dist
